FROM node:lts-slim

WORKDIR /www

RUN apt-get update && apt-get install curl -y \
    && curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz \
    && gunzip elm.gz \
    && chmod +x elm \
    && mv elm /usr/local/bin/elm \
    && npm install --save-dev elm-test

COPY elm.json ./
